### ISSUE TITLE
Regarding HObjectModel3D intensity values

### ISSUE THREAD

**Issue by neerja123-gupta** [asr-ros/asr_halcon_bridge#6]
Hello, 

We are using this repository for converting a PointCloud2 ROS msg to HObjectModel3D. We are using toHalconCopy function, where it calls HObjectModel3D(x_coords, y_coords, z_coords). However, I was just wondering do you know any way by which we can access the intensity(rgb) values as well, because we are loosing texture information after conversion. 
Any help would be highly appreciated. 

Thanks.

**Comment by Tobi2001** [comment]
Unfortunately I can't really help you much further with your problem since I haven't used Halcon in a while and as you've noticed this repository only supports converting the XYZ coordinates. You should probably check the official API documentation or contact the Halcon support to solve your problem.
I'll close this ticket for now since the problem doesn't seem directly connected to this repository.
